#ifndef CLARION_TRINITY_DEFINITIONS_HH
#define CLARION_TRINITY_DEFINITIONS_HH

#define MAX_GAGG_CRYSTALS 128
#define MAX_GAGG_ID 600
#define CT_MAX_CRATES 2
#define CT_MAX_SLOTS_PER_CRATE 13
#define CT_MAX_CHANNELS_PER_BOARD 16
#define MAX_HITS_PER_CLOVER 10
#define MAX_GAMMAS 20
#define MAX_CLOVERS 20

#endif
